### ISSUE TITLE
Population

### ISSUE THREAD

**Issue by MutantAc** [Group11Software/Coursework#14]
- [x] The population of the world.
- [x] The population of a continent.
- [x] The population of a region.
- [x] The population of a country.
- [x] The population of a district.
- [x] The population of a city.

**Comment by MutantAc** [comment]
Example population complete

**Comment by 40682339** [comment]
Population Of the world report generated + Test Working

**Comment by 40682339** [comment]
Population of a continent report generated + Test Working

**Comment by 40682339** [comment]
Population of a country report generated (Example: Iran) + Test Working
